/**
 * styleKits/editorial — 编辑版式族（12 种）。
 * 版式即风格：从 Vogue 大写字距到日系文库本，每种是一套完整的排印传统。
 */
import type { StyleKit } from '../styleKits';

/* eslint-disable max-len */

export const EDITORIAL_KITS: StyleKit[] = [
  {
    id: 'vogue', family: '编辑版式', label: '时装大刊',
    vibe: '全大写衬线刊头、超宽字距、极简黑白、页码细节——时尚/美妆/人物专访',
    cssVars: { '--fx-primary': '#f6f4f0', '--fx-accent': '#111111', '--fx-accent2': '#b8a88f', '--fx-text': '#111111', '--fx-surface': 'rgba(17,17,17,0.04)' },
    fontPairing: 'luxury',
    bgCss: '#f6f4f0',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div style="position:absolute;left:50%;top:54px;transform:translateX(-50%);font-family:'Playfair Display',serif;font-size:30px;letter-spacing:.58em;color:rgba(17,17,17,.85)">ÉDITION</div><div style="position:absolute;left:8%;right:8%;top:110px;height:1px;background:rgba(17,17,17,.3)"></div></div>`,
    foregroundHtml: `<div style="position:absolute;left:50%;bottom:44px;transform:translateX(-50%);font-size:15px;letter-spacing:.32em;color:rgba(17,17,17,.45)">— 042 —</div>`,
    motionNotes: '克制到骄傲：一次 maskReveal(bottom, outExpo 0.9s) 揭开大标题即可；字距 .2em+ 全大写；黑白为主，米金 accent2 只做一根细线；忌一切弹跳',
  },
  {
    id: 'kinfolk', family: '编辑版式', label: '慢生活杂志',
    vibe: '奶油底大留白、小字号衬线、细线分隔、呼吸感排版——生活方式/咖啡/家居',
    cssVars: { '--fx-primary': '#f2ede4', '--fx-accent': '#4a453c', '--fx-accent2': '#a89c88', '--fx-text': '#4a453c', '--fx-surface': 'rgba(74,69,60,0.05)' },
    fontPairing: 'editorial',
    bgCss: 'linear-gradient(180deg,#f4efe6 0%,#ede7db 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:.5"></div><div style="position:absolute;left:12%;top:20%;bottom:20%;width:1px;background:rgba(74,69,60,.18)"></div></div>`,
    motionNotes: '呼吸节奏：一切 opacity 慢淡入（1.2s+ outQuad），元素间隔 0.4s 依次；文字小而精（kp-h3 以下），留白 >50%；忌大字忌快动作——安静是态度',
  },
  {
    id: 'tabloid', family: '编辑版式', label: '爆点小报',
    vibe: '大黄底红黑爆炸标题、倾斜贴条、感叹号——八卦/爆料/吐槽/热点',
    cssVars: { '--fx-primary': '#f5d90a', '--fx-accent': '#d7191c', '--fx-accent2': '#111111', '--fx-text': '#111111', '--fx-surface': '#ffffff' },
    fontPairing: 'minimal',
    bgCss: '#f5d90a',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div style="position:absolute;left:-5%;top:9%;width:480px;height:86px;background:#d7191c;transform:rotate(-4deg)"></div><div style="position:absolute;right:-4%;bottom:16%;width:400px;height:70px;background:#111;transform:rotate(3deg)"></div><div style="position:absolute;right:10%;top:10%;width:150px;height:150px;background:#fff;clip-path:polygon(50% 0,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%);transform:rotate(12deg)"></div></div>`,
    css: `.kit-tabloid-strip{background:#d7191c;color:#fff;padding:.12em .4em;transform:rotate(-2deg);display:inline-block}`,
    motionNotes: '砸出来的新闻：标题 scale 3→1 inExpo 撞入+shake(amp 14)；贴条 kit-tabloid-strip 逐条拍上（stagger + 各自 rotate 错位）；快、猛、密，允许两次闪白',
  },
  {
    id: 'academia', family: '编辑版式', label: '古典学术',
    vibe: '羊皮纸、脚注编号、拉丁引文斜体、藏书票——知识考古/书评/深度长文',
    cssVars: { '--fx-primary': '#efe6d3', '--fx-accent': '#6b1f1a', '--fx-accent2': '#3f5a45', '--fx-text': '#33291c', '--fx-surface': 'rgba(51,41,28,0.05)' },
    fontPairing: 'editorial',
    bgCss: 'radial-gradient(ellipse 95% 85% at 50% 30%,#f2e9d6 0%,#e6dbc2 80%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:.9"></div><div style="position:absolute;left:9%;top:12%;font-family:'Playfair Display',serif;font-size:280px;line-height:1;color:rgba(107,31,26,.1)">§</div><div style="position:absolute;left:8%;right:8%;bottom:100px;height:1px;background:rgba(51,41,28,.35)"></div><div style="position:absolute;left:8%;bottom:64px;font-family:'Noto Serif SC',serif;font-size:16px;color:rgba(51,41,28,.55);font-style:italic">¹ Ibid., p.42 — ² op. cit.</div></div>`,
    motionNotes: '翻页节奏：段落 maskReveal(top) 如目光下移；编号上标红色小字延迟出现；重点句 kp-underline 描线（lineDraw 感）；慢而沉',
  },
  {
    id: 'gridzine', family: '编辑版式', label: '荷兰网格实验',
    vibe: '裸露网格线、旋转文字块、超大页码、荧光点缀——设计圈/作品集/先锋刊物',
    cssVars: { '--fx-primary': '#ebebe6', '--fx-accent': '#ff4d00', '--fx-accent2': '#1a1a1a', '--fx-text': '#1a1a1a', '--fx-surface': 'rgba(26,26,26,0.05)' },
    fontPairing: 'minimal',
    bgCss: '#ebebe6',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-grid" style="position:absolute;inset:0;opacity:.9"></div><div style="position:absolute;right:3%;bottom:-6%;font-size:420px;font-weight:800;line-height:1;letter-spacing:-0.05em;color:transparent;-webkit-text-stroke:2px rgba(26,26,26,.3)">04</div><div style="position:absolute;left:64px;top:64px;width:14px;height:14px;background:#ff4d00"></div></div>`,
    css: `.kit-gridzine-rot{writing-mode:vertical-rl;transform:rotate(180deg);letter-spacing:.14em}`,
    motionNotes: '结构外露：网格先在（不动），内容块沿网格线 maskReveal 精确入位；一个文字块用 kit-gridzine-rot 竖排制造张力；荧光橙只给一个小方块或一个词',
  },
  {
    id: 'bunko', family: '编辑版式', label: '日系文库本',
    vibe: '素色书封、窄开本比例框、书腰、假名注音细节——书单/读书/治愈系',
    cssVars: { '--fx-primary': '#e6e2d8', '--fx-accent': '#b5493a', '--fx-accent2': '#5f6b5d', '--fx-text': '#39362f', '--fx-surface': '#f2efe7' },
    fontPairing: 'literary',
    bgCss: 'linear-gradient(170deg,#e9e5da 0%,#ddd8ca 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:.6"></div><div style="position:absolute;left:10%;top:14%;bottom:14%;width:440px;background:#f2efe7;box-shadow:0 16px 44px rgba(57,54,47,.22)"><div style="position:absolute;left:0;right:0;bottom:88px;height:96px;background:#b5493a;opacity:.92"></div><div style="position:absolute;left:26px;top:36px;width:2px;bottom:200px;background:rgba(57,54,47,.2)"></div></div></div>`,
    motionNotes: '掀页温柔：书封元素 rotate y 感用 scaleX 0.92→1 + x 位移模拟开合；文字竖排 kp-vert 自右向左 stagger；书腰红条 maskReveal left 最后系上；轻慢',
  },
  {
    id: 'manifesto', family: '编辑版式', label: '黑体宣言',
    vibe: '整屏纯黑大字、行间紧咬、一个红词、无装饰——观点输出/态度短打',
    cssVars: { '--fx-primary': '#0d0d0d', '--fx-accent': '#ff2e2e', '--fx-accent2': '#5c5c5c', '--fx-text': '#f2f2f2', '--fx-surface': 'rgba(242,242,242,0.06)' },
    fontPairing: 'minimal',
    bgCss: '#0d0d0d',
    motionNotes: '文字即全部：无任何装饰层——大字（kp-h1 以上）逐行 maskReveal bottom 硬切上屏（0.3s，行距 0.95 紧咬），关键词红色重拍配 shake 一次；黑白红三色纪律',
  },
  {
    id: 'fieldnotes', family: '编辑版式', label: '田野手帐',
    vibe: '牛皮纸、贴纸标签、虚线路径、图钉与批注——旅行攻略/探店/测评过程记录',
    cssVars: { '--fx-primary': '#d9c9a3', '--fx-accent': '#c14b2a', '--fx-accent2': '#4f6448', '--fx-text': '#3d3222', '--fx-surface': '#f0e8d4' },
    fontPairing: 'literary',
    bgCss: 'linear-gradient(165deg,#dccca7 0%,#cdbb92 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:1.1"></div><svg style="position:absolute;inset:0;opacity:.75" width="1920" height="1080" fill="none"><path d="M 260 780 C 500 660 640 820 900 700 S 1360 520 1620 400" stroke="#c14b2a" stroke-width="3.5" stroke-dasharray="4 16" stroke-linecap="round"/><circle cx="260" cy="780" r="10" fill="#c14b2a"/><circle cx="1620" cy="400" r="10" fill="#c14b2a"/><circle cx="1620" cy="400" r="18" stroke="#c14b2a" stroke-width="2.5"/></svg><div style="position:absolute;left:14%;top:12%;width:190px;height:54px;background:#f0e8d4;transform:rotate(-4deg);box-shadow:0 4px 12px rgba(61,50,34,.25)"></div></div>`,
    motionNotes: '手帐生长：虚线路径 lineDraw 是主线叙事（起点→终点）、贴纸卡 spring 拍上带 rotate 错位、图钉点 scale 弹出；手写感 kp-serif 斜体标注',
  },
  {
    id: 'gallery', family: '编辑版式', label: '白盒美术馆',
    vibe: '纯白展墙、作品留白居中、展签小字、射灯投影——作品展示/艺术解读/高审美开箱',
    cssVars: { '--fx-primary': '#fafafa', '--fx-accent': '#1c1c1c', '--fx-accent2': '#8f8f8f', '--fx-text': '#1c1c1c', '--fx-surface': 'rgba(28,28,28,0.04)' },
    fontPairing: 'minimal',
    bgCss: 'linear-gradient(180deg,#fcfcfc 0%,#f2f2f2 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div style="position:absolute;left:50%;top:0;width:900px;height:560px;transform:translateX(-50%);background:radial-gradient(ellipse 55% 80% at 50% 0%,rgba(0,0,0,.055),transparent 70%)"></div><div style="position:absolute;left:0;right:0;bottom:14%;height:1px;background:rgba(28,28,28,.1)"></div></div>`,
    foregroundHtml: `<div style="position:absolute;right:12%;bottom:9%;text-align:left;font-size:15px;line-height:1.8;color:rgba(28,28,28,.55)"><span style="font-weight:700;color:rgba(28,28,28,.8)">无题 №7</span><br/>综合材料 · 2026</div>`,
    motionNotes: '策展节奏：主体如挂画缓缓浮现（opacity+y 20→0, 1.2s outQuart），展签延迟 0.8s 淡入；一屏一件作品；克制留白，忌多元素同屏',
  },
  {
    id: 'annualreport', family: '编辑版式', label: '年报信息图',
    vibe: '藏青金双色、大数字断行、分割线体系、图例圆点——总结盘点/财报/数据故事',
    cssVars: { '--fx-primary': '#101d33', '--fx-accent': '#e3b04b', '--fx-accent2': '#5d759e', '--fx-text': '#eef2f9', '--fx-surface': 'rgba(93,117,158,0.12)' },
    fontPairing: 'minimal',
    bgCss: 'linear-gradient(165deg,#13223c 0%,#0d1829 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div style="position:absolute;right:6%;top:12%;bottom:12%;width:1px;background:rgba(227,176,75,.35)"></div><div style="position:absolute;right:calc(6% - 4px);top:12%;width:9px;height:9px;border-radius:50%;background:#e3b04b"></div><div style="position:absolute;left:6%;bottom:12%;display:flex;gap:26px;font-size:15px;color:rgba(238,242,249,.55)"><span style="display:flex;align-items:center;gap:8px"><i style="width:10px;height:10px;border-radius:50%;background:#e3b04b;display:inline-block"></i>本期</span><span style="display:flex;align-items:center;gap:8px"><i style="width:10px;height:10px;border-radius:50%;background:#5d759e;display:inline-block"></i>同期</span></div></div>`,
    motionNotes: '数字叙事：kp-mega 大数字 numberRoll（金色）+ 单位小字灰蓝；分割线 scaleY/scaleX 生长构建版面骨架先行；条形 scaleX 依次生长；稳重 outExpo',
  },
  {
    id: 'blackboard', family: '编辑版式', label: '粉笔黑板',
    vibe: '墨绿板面、粉笔手写线、板擦痕迹、重点圈划——授课/干货/公式推导',
    cssVars: { '--fx-primary': '#26352c', '--fx-accent': '#f5e9c8', '--fx-accent2': '#e8a5a5', '--fx-text': '#f0ead6', '--fx-surface': 'rgba(240,234,214,0.07)' },
    fontPairing: 'literary',
    bgCss: 'radial-gradient(ellipse 90% 85% at 50% 45%,#2b3c32 0%,#1f2d25 80%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:.8"></div><div style="position:absolute;left:10%;top:20%;width:340px;height:90px;background:rgba(240,234,214,.05);filter:blur(10px);transform:rotate(-3deg)"></div><div style="position:absolute;right:14%;bottom:24%;width:280px;height:70px;background:rgba(240,234,214,.045);filter:blur(9px);transform:rotate(2deg)"></div><div style="position:absolute;left:0;right:0;bottom:0;height:26px;background:#54432e"></div><div style="position:absolute;left:12%;bottom:14px;width:130px;height:20px;background:#e8ddc0;border-radius:3px;box-shadow:0 3px 6px rgba(0,0,0,.3)"></div></div>`,
    motionNotes: '板书节奏：一切文字/线条 lineDraw 或 typewriter 手写出（这是核心）、重点用 accent2 粉红粉笔圈（circleMark 式 SVG lineDraw）；讲一点写一点，stagger 大（0.4s+）',
  },
  {
    id: 'filmscript', family: '编辑版式', label: '剧本围读',
    vibe: '打字机纸稿、场景标注 INT/EXT、对白缩进、咖啡渍——影视解说/编剧/幕后',
    cssVars: { '--fx-primary': '#ece7db', '--fx-accent': '#2b2823', '--fx-accent2': '#b5563c', '--fx-text': '#2b2823', '--fx-surface': 'rgba(43,40,35,0.05)' },
    fontPairing: 'tech',
    bgCss: 'linear-gradient(180deg,#eee9dd 0%,#e4ddcd 100%)',
    backdropHtml: `<div style="position:absolute;inset:0;overflow:hidden"><div class="kp-noise" style="position:absolute;inset:0;opacity:.7"></div><div style="position:absolute;left:8%;top:8%;font-family:'JetBrains Mono',monospace;font-size:19px;line-height:2.4;color:rgba(43,40,35,.3);white-space:pre">FADE IN:\n\nINT. 剪辑室 - 夜</div><div style="position:absolute;right:12%;top:14%;width:120px;height:120px;border-radius:50%;border:14px solid rgba(181,86,60,.13)"></div><div style="position:absolute;left:6%;top:0;bottom:0;width:1px;background:rgba(181,86,60,.35)"></div></div>`,
    motionNotes: '打字机是唯一动效来源：所有文字 typewriter（charDur 0.05，等宽字）；场景标注全大写先行；关键台词后缩进出现；黑白克制，节奏由文字长短天然形成',
  },
];
