/* KPMotion runtime — generated by scripts/build-motion-runtime.mjs. DO NOT EDIT.
 * KP_MOTION_VERSION=a274e2e924
 */
"use strict";
(() => {
  // src/lib/motion/spec.ts
  function resolveTimeRef(ref, beats, fallback = 0) {
    if (ref == null) return fallback;
    if (typeof ref === "number") return ref;
    const m = /^beat:(\d+)\s*(?:([+-])\s*([\d.]+))?$/.exec(String(ref).trim());
    if (!m) return fallback;
    const base = beats?.[Number(m[1])];
    if (base == null) return fallback;
    const off = m[3] ? parseFloat(m[3]) * (m[2] === "-" ? -1 : 1) : 0;
    return base + off;
  }

  // src/lib/motion/runtime/easing.ts
  var c1 = 1.70158;
  var c3 = c1 + 1;
  var EASINGS = {
    linear: (p) => p,
    inQuad: (p) => p * p,
    outQuad: (p) => 1 - (1 - p) * (1 - p),
    inOutQuad: (p) => p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2,
    inCubic: (p) => p * p * p,
    outCubic: (p) => 1 - Math.pow(1 - p, 3),
    inOutCubic: (p) => p < 0.5 ? 4 * p * p * p : 1 - Math.pow(-2 * p + 2, 3) / 2,
    outQuart: (p) => 1 - Math.pow(1 - p, 4),
    inExpo: (p) => p === 0 ? 0 : Math.pow(2, 10 * p - 10),
    outExpo: (p) => p === 1 ? 1 : 1 - Math.pow(2, -10 * p),
    inOutExpo: (p) => p === 0 ? 0 : p === 1 ? 1 : p < 0.5 ? Math.pow(2, 20 * p - 10) / 2 : (2 - Math.pow(2, -20 * p + 10)) / 2,
    inBack: (p) => c3 * p * p * p - c1 * p * p,
    outBack: (p) => 1 + c3 * Math.pow(p - 1, 3) + c1 * Math.pow(p - 1, 2),
    outElastic: (p) => {
      if (p === 0 || p === 1) return p;
      return Math.pow(2, -10 * p) * Math.sin((p * 10 - 0.75) * (2 * Math.PI / 3)) + 1;
    },
    outBounce: (p) => {
      const n1 = 7.5625;
      const d1 = 2.75;
      if (p < 1 / d1) return n1 * p * p;
      if (p < 2 / d1) return n1 * (p -= 1.5 / d1) * p + 0.75;
      if (p < 2.5 / d1) return n1 * (p -= 2.25 / d1) * p + 0.9375;
      return n1 * (p -= 2.625 / d1) * p + 0.984375;
    }
  };
  function easeOf(name) {
    return name && EASINGS[name] || EASINGS.outCubic;
  }
  function springDecay(tau, params) {
    if (tau <= 0) return 1;
    const stiffness = Math.max(1, params?.stiffness ?? 170);
    const damping = Math.max(0.1, params?.damping ?? 14);
    const w0 = Math.sqrt(stiffness);
    const zeta = damping / (2 * w0);
    if (zeta < 1) {
      const wd = w0 * Math.sqrt(1 - zeta * zeta);
      return Math.exp(-zeta * w0 * tau) * (Math.cos(wd * tau) + zeta * w0 / wd * Math.sin(wd * tau));
    }
    const decay = Math.exp(-w0 * tau);
    return decay * (1 + w0 * tau);
  }

  // src/lib/motion/runtime/evaluate.ts
  var TRACK_DEFAULTS = {
    x: 0,
    y: 0,
    scale: 1,
    scaleX: 1,
    scaleY: 1,
    rotate: 0,
    opacity: 1,
    blur: 0
  };
  function evalTrack(kf, t) {
    if (kf.length === 0) return 0;
    if (t <= kf[0].t) return kf[0].v;
    const last = kf[kf.length - 1];
    if (t >= last.t) {
      if (last.spring && kf.length >= 2) {
        const prev = kf[kf.length - 2];
        return last.v + (prev.v - last.v) * springDecay(t - prev.t, last.spring);
      }
      return last.v;
    }
    for (let i = 1; i < kf.length; i++) {
      if (t < kf[i].t) {
        const prev = kf[i - 1];
        const cur = kf[i];
        if (cur.spring) {
          return cur.v + (prev.v - cur.v) * springDecay(t - prev.t, cur.spring);
        }
        const span = Math.max(1e-6, cur.t - prev.t);
        const p = (t - prev.t) / span;
        return prev.v + (cur.v - prev.v) * easeOf(cur.ease)(p);
      }
    }
    return last.v;
  }
  function evalTracks(tracks, t) {
    const out = { ...TRACK_DEFAULTS };
    for (const tr of tracks) {
      out[tr.prop] = evalTrack(tr.kf, t);
    }
    return out;
  }
  function compileTrack(track, resolveT) {
    const kf = track.kf.map((k) => ({ t: resolveT(k.t, 0), v: k.v, ease: k.ease, spring: k.spring })).sort((a, b) => a.t - b.t);
    return { prop: track.prop, kf };
  }
  function clamp01(p) {
    return p < 0 ? 0 : p > 1 ? 1 : p;
  }

  // src/lib/motion/runtime/noise.ts
  function mulberry32(seed) {
    let a = seed >>> 0;
    return () => {
      a |= 0;
      a = a + 1831565813 | 0;
      let t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  function seededSines(seed, freq) {
    const rand = mulberry32(Math.floor(seed * 1013904223) + 1);
    const f1 = freq * (0.9 + rand() * 0.2);
    const f2 = freq * (1.7 + rand() * 0.6);
    const f3 = freq * (2.9 + rand() * 0.8);
    const p1 = rand() * Math.PI * 2;
    const p2 = rand() * Math.PI * 2;
    const p3 = rand() * Math.PI * 2;
    const TWO_PI = Math.PI * 2;
    return (t) => Math.sin(TWO_PI * f1 * t + p1) * 0.55 + Math.sin(TWO_PI * f2 * t + p2) * 0.3 + Math.sin(TWO_PI * f3 * t + p3) * 0.15;
  }

  // src/lib/motion/runtime/text.ts
  function splitText(el, mode) {
    const units = [];
    const textNodes = [];
    for (const node of Array.from(el.childNodes)) {
      if (node.nodeType === 3 && node.textContent && node.textContent.trim()) textNodes.push(node);
    }
    for (const node of textNodes) {
      const text = node.textContent ?? "";
      const frag = el.ownerDocument.createDocumentFragment();
      const pieces = mode === "char" ? [...text] : text.split(/(\s+)/).flatMap(splitWordPiece);
      for (const piece of pieces) {
        if (!piece) continue;
        if (/^\s+$/.test(piece)) {
          frag.appendChild(el.ownerDocument.createTextNode(piece));
          continue;
        }
        const span = el.ownerDocument.createElement("span");
        span.className = "kp-split-unit";
        span.style.display = "inline-block";
        span.style.whiteSpace = "pre";
        span.textContent = piece;
        frag.appendChild(span);
        units.push({ el: span });
      }
      node.replaceWith(frag);
    }
    return units;
  }
  function splitWordPiece(piece) {
    if (/^\s+$/.test(piece) || !piece) return [piece];
    if (/[一-鿿㐀-䶿　-〿]/.test(piece)) return [...piece];
    return [piece];
  }

  // src/lib/motion/runtime/effects.ts
  function resetDelta(d) {
    d.dx = 0;
    d.dy = 0;
    d.drot = 0;
    d.dscale = 1;
    d.opacityMul = 1;
    d.clipPath = null;
  }
  function compileKineticText(fx, ctx) {
    const units = splitText(ctx.el, fx.split ?? "char");
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.5;
    const stagger = fx.stagger ?? 0.045;
    const from = { x: 0, y: 60, rotate: 0, scale: 1, opacity: 0, ...fx.from ?? {} };
    const ease = easeOf(fx.ease ?? "outBack");
    const spring = fx.spring;
    return {
      apply(t) {
        for (let i = 0; i < units.length; i++) {
          const local = t - at - i * stagger;
          let p;
          if (spring) {
            p = local <= 0 ? 0 : 1 - springDecay(local, spring);
          } else {
            p = ease(clamp01(local / Math.max(1e-6, dur)));
          }
          const inv = 1 - p;
          const s = units[i].el.style;
          s.transform = `translate(${(from.x * inv).toFixed(2)}px, ${(from.y * inv).toFixed(2)}px) rotate(${(from.rotate * inv).toFixed(2)}deg) scale(${(1 + (from.scale - 1) * inv).toFixed(4)})`;
          s.opacity = String(clamp01(from.opacity + (1 - from.opacity) * clamp01(p)));
        }
      }
    };
  }
  function compileMaskReveal(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.6;
    const dir = fx.dir ?? "left";
    const ease = easeOf(fx.ease ?? "outExpo");
    const isOut = Boolean(fx.out);
    return {
      apply(t, delta) {
        let p = ease(clamp01((t - at) / Math.max(1e-6, dur)));
        if (isOut) p = 1 - p;
        const hide = ((1 - p) * 100).toFixed(2);
        switch (dir) {
          case "left":
            delta.clipPath = `inset(0 ${hide}% 0 0)`;
            break;
          case "right":
            delta.clipPath = `inset(0 0 0 ${hide}%)`;
            break;
          case "top":
            delta.clipPath = `inset(0 0 ${hide}% 0)`;
            break;
          case "bottom":
            delta.clipPath = `inset(${hide}% 0 0 0)`;
            break;
          case "center":
            delta.clipPath = `circle(${(p * 75).toFixed(2)}% at 50% 50%)`;
            break;
        }
      }
    };
  }
  function compileShake(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.35;
    const amp = fx.amp ?? 12;
    const freq = fx.freq ?? 18;
    const rotAmp = fx.rotAmp ?? amp / 10;
    const seed = fx.seed ?? 1;
    const nx = seededSines(seed, freq);
    const ny = seededSines(seed + 101, freq * 1.13);
    const nr = seededSines(seed + 202, freq * 0.87);
    return {
      apply(t, delta) {
        const local = t - at;
        if (local < 0 || local > dur) return;
        const env = Math.sin(Math.PI * clamp01(local / dur)) ** 0.7;
        delta.dx += nx(local) * amp * env;
        delta.dy += ny(local) * amp * env;
        delta.drot += nr(local) * rotAmp * env;
      }
    };
  }
  function compileLineDraw(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.9;
    const stagger = fx.stagger ?? 0.08;
    const ease = easeOf(fx.ease ?? "inOutCubic");
    const paths = [];
    const nodes = ctx.el.querySelectorAll("path, circle, ellipse, line, polyline, polygon, rect");
    nodes.forEach((el) => {
      let len = 0;
      try {
        len = el.getTotalLength();
      } catch {
        len = 0;
      }
      if (!len || !Number.isFinite(len)) len = 1e3;
      el.style.strokeDasharray = `${len}`;
      el.style.strokeDashoffset = `${len}`;
      paths.push({ el, len });
    });
    return {
      apply(t) {
        for (let i = 0; i < paths.length; i++) {
          const p = ease(clamp01((t - at - i * stagger) / Math.max(1e-6, dur)));
          paths[i].el.style.strokeDashoffset = `${(paths[i].len * (1 - p)).toFixed(2)}`;
        }
      }
    };
  }
  function formatNumber(v, fx) {
    const decimals = fx.decimals ?? 0;
    const prefix = fx.prefix ?? "";
    const suffix = fx.suffix ?? "";
    let body;
    switch (fx.format ?? "plain") {
      case "comma":
        body = v.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
        break;
      case "compact-cn": {
        const abs = Math.abs(v);
        if (abs >= 1e8) body = `${(v / 1e8).toFixed(abs >= 1e9 ? 0 : 1)}\u4EBF`;
        else if (abs >= 1e4) body = `${(v / 1e4).toFixed(abs >= 1e5 ? 0 : 1)}\u4E07`;
        else body = `${Math.round(v)}`;
        break;
      }
      case "percent":
        body = `${v.toFixed(decimals)}%`;
        break;
      default:
        body = v.toFixed(decimals);
    }
    return `${prefix}${body}${suffix}`;
  }
  function compileNumberRoll(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 1.2;
    const from = fx.from ?? 0;
    const to = fx.to;
    const ease = easeOf(fx.ease ?? "outExpo");
    const target = ctx.el.querySelector(".kp-num-value") ?? ctx.el;
    return {
      apply(t) {
        const p = ease(clamp01((t - at) / Math.max(1e-6, dur)));
        target.textContent = formatNumber(from + (to - from) * p, fx);
      }
    };
  }
  function compileTrail(fx, ctx) {
    const copies = Math.max(1, Math.min(4, fx.copies ?? 3));
    const lag = fx.lag ?? 0.06;
    const fade = fx.fade ?? 0.5;
    const ghosts = [];
    const parent = ctx.el.parentElement;
    if (!parent) return { ghosts };
    for (let i = 1; i <= copies; i++) {
      const ghost = ctx.el.cloneNode(true);
      ghost.setAttribute("aria-hidden", "true");
      ghost.classList.add("kp-trail-ghost");
      ghost.style.pointerEvents = "none";
      parent.insertBefore(ghost, ctx.el);
      ghosts.push({ el: ghost, lag: lag * i, fade: Math.pow(fade, i) });
    }
    return { ghosts };
  }
  function coordPx(v, total) {
    if (typeof v === "number") return v;
    const s = String(v).trim();
    if (s.endsWith("%")) return parseFloat(s) / 100 * total;
    return parseFloat(s) || 0;
  }
  function compileMagnify(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 1.5;
    const cx = coordPx(fx.region.x, ctx.stageW);
    const cy = coordPx(fx.region.y, ctx.stageH);
    const r = fx.region.r;
    const dim = fx.dim ?? 0.45;
    const color = fx.color ?? "var(--fx-accent)";
    const doc = ctx.el.ownerDocument;
    const overlay = doc.createElement("div");
    overlay.className = "kp-magnify-dim";
    overlay.style.cssText = `position:absolute;inset:0;pointer-events:none;background:rgba(0,0,0,${dim});opacity:0;`;
    const ring = doc.createElement("div");
    ring.className = "kp-magnify-ring";
    ring.style.cssText = `position:absolute;left:${cx - r}px;top:${cy - r}px;width:${r * 2}px;height:${r * 2}px;border:6px solid ${color};border-radius:50%;box-shadow:0 0 40px rgba(0,0,0,0.4);pointer-events:none;opacity:0;`;
    ctx.el.appendChild(overlay);
    ctx.el.appendChild(ring);
    const easeIn = easeOf("outCubic");
    return {
      apply(t) {
        const local = t - at;
        const inP = easeIn(clamp01(local / 0.35));
        const outP = easeIn(clamp01((local - dur + 0.3) / 0.3));
        const vis = local < 0 ? 0 : inP * (1 - outP);
        overlay.style.opacity = String(vis);
        overlay.style.webkitMaskImage = `radial-gradient(circle ${r}px at ${cx}px ${cy}px, transparent 98%, #000 100%)`;
        overlay.style.maskImage = `radial-gradient(circle ${r}px at ${cx}px ${cy}px, transparent 98%, #000 100%)`;
        ring.style.opacity = String(vis);
        const pulse = 1 + 0.03 * Math.sin(Math.max(0, local) * Math.PI * 2 * 1.2);
        ring.style.transform = `scale(${(vis > 0 ? pulse : 0.9).toFixed(4)})`;
      }
    };
  }
  function compileTypewriter(fx, ctx) {
    const units = splitText(ctx.el, "char");
    const at = ctx.resolveT(fx.at, 0);
    const charDur = fx.charDur ?? 0.06;
    const useCursor = fx.cursor !== false;
    let cursor = null;
    if (useCursor) {
      cursor = ctx.el.ownerDocument.createElement("span");
      cursor.className = "kp-tw-cursor";
      cursor.style.cssText = `display:inline-block;width:0.08em;height:1em;vertical-align:-0.12em;background:${fx.cursorColor ?? "var(--fx-accent)"};margin-left:0.05em;`;
      ctx.el.appendChild(cursor);
    }
    const totalDur = units.length * charDur;
    return {
      apply(t) {
        const local = t - at;
        const shown = local <= 0 ? 0 : Math.min(units.length, Math.floor(local / charDur) + 1);
        for (let i = 0; i < units.length; i++) {
          units[i].el.style.opacity = i < shown ? "1" : "0";
        }
        if (cursor) {
          const done = local - totalDur;
          const blink = Math.floor(Math.max(0, local) * 2.2) % 2 === 0 ? 1 : 0;
          cursor.style.opacity = local < 0 || done > 1.2 ? "0" : String(blink);
        }
      }
    };
  }
  function compileGlitch(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.5;
    const amp = fx.amp ?? 6;
    const freq = fx.freq ?? 14;
    const seed = fx.seed ?? 1;
    const parent = ctx.el.parentElement;
    const copies = [];
    if (parent) {
      for (const [color, cls] of [["rgba(255,0,64,0.8)", "kp-glitch-r"], ["rgba(0,224,255,0.8)", "kp-glitch-c"]]) {
        const ghost = ctx.el.cloneNode(true);
        ghost.setAttribute("aria-hidden", "true");
        ghost.classList.add(cls);
        ghost.style.pointerEvents = "none";
        ghost.style.color = color;
        ghost.style.opacity = "0";
        parent.insertBefore(ghost, ctx.el);
        copies.push(ghost);
      }
    }
    const nx = seededSines(seed, freq);
    const nSlice = seededSines(seed + 51, freq * 1.6);
    return {
      apply(t, delta) {
        const local = t - at;
        const active = local >= 0 && local <= dur;
        const env = active ? Math.pow(1 - local / dur, 0.6) : 0;
        for (let i = 0; i < copies.length; i++) {
          const dir = i === 0 ? 1 : -1;
          copies[i].style.opacity = String(0.75 * env);
          copies[i].style.transform = `translate(${(nx(local + i) * amp * dir * env).toFixed(2)}px, 0)`;
        }
        if (active) {
          const bandY = (nSlice(local) * 0.5 + 0.5) * 80;
          const bandH = 12 + (nx(local * 1.3) * 0.5 + 0.5) * 18;
          delta.dx += nx(local * 2.1) * amp * 0.6 * env;
          if (Math.floor(local * freq) % 3 === 0) {
            delta.clipPath = `inset(${bandY.toFixed(1)}% 0 ${Math.max(0, 100 - bandY - bandH).toFixed(1)}% 0)`;
          }
        }
      }
    };
  }
  function compileShine(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 1.1;
    const every = fx.every ?? 0;
    const angle = fx.angle ?? 115;
    const strength = fx.strength ?? 0.5;
    const doc = ctx.el.ownerDocument;
    const band = doc.createElement("div");
    band.className = "kp-shine-band";
    band.style.cssText = `position:absolute;inset:-10%;pointer-events:none;opacity:0;mix-blend-mode:screen;background:linear-gradient(${angle}deg, transparent 42%, rgba(255,255,255,${strength}) 50%, transparent 58%);background-size:280% 280%;`;
    ctx.el.appendChild(band);
    const ease = easeOf("inOutCubic");
    return {
      apply(t) {
        let local = t - at;
        if (every > 0 && local > 0) local = local % Math.max(every, dur);
        const p = local < 0 || local > dur ? -1 : ease(clamp01(local / dur));
        if (p < 0) {
          band.style.opacity = "0";
          return;
        }
        band.style.opacity = "1";
        band.style.backgroundPosition = `${(100 - p * 200).toFixed(2)}% 50%`;
      }
    };
  }
  function compileGradientShift(fx, ctx) {
    const period = Math.max(1, fx.period ?? 6);
    const angle = fx.angle ?? 120;
    const colors = fx.colors?.length ? fx.colors : ["var(--fx-accent)", "var(--fx-accent2)"];
    const mode = fx.mode ?? "text";
    const stops = [...colors, colors[0]].join(", ");
    const el = ctx.el;
    el.style.backgroundImage = `linear-gradient(${angle}deg, ${stops})`;
    el.style.backgroundSize = "300% 300%";
    if (mode === "text") {
      el.style.webkitBackgroundClip = "text";
      el.style.backgroundClip = "text";
      el.style.webkitTextFillColor = "transparent";
      el.style.color = "transparent";
    }
    return {
      apply(t) {
        const p = t % period / period;
        el.style.backgroundPosition = `${(p * 200).toFixed(2)}% 50%`;
      }
    };
  }
  function compilePathMove(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 1.5;
    const ease = easeOf(fx.ease ?? "inOutCubic");
    const { via, to } = fx;
    const orient = Boolean(fx.orient);
    return {
      apply(t, delta) {
        const p = ease(clamp01((t - at) / Math.max(1e-6, dur)));
        const inv = 1 - p;
        delta.dx += 2 * inv * p * via.x + p * p * to.x;
        delta.dy += 2 * inv * p * via.y + p * p * to.y;
        if (orient) {
          const tx = 2 * inv * via.x + 2 * p * (to.x - via.x);
          const ty = 2 * inv * via.y + 2 * p * (to.y - via.y);
          delta.drot += Math.atan2(ty, tx) * (180 / Math.PI);
        }
      }
    };
  }
  function compileWaveText(fx, ctx) {
    const units = splitText(ctx.el, "char");
    const at = ctx.resolveT(fx.at, 0);
    const amp = fx.amp ?? 10;
    const period = Math.max(0.5, fx.period ?? 2.4);
    const phaseStep = fx.phaseStep ?? 0.12;
    const rotAmp = fx.rotAmp ?? 0;
    const TWO_PI = Math.PI * 2;
    const inner = units.map((u) => {
      const w = ctx.el.ownerDocument.createElement("span");
      w.style.display = "inline-block";
      while (u.el.firstChild) w.appendChild(u.el.firstChild);
      u.el.appendChild(w);
      return w;
    });
    return {
      apply(t) {
        const local = t - at;
        const ramp = local <= 0 ? 0 : clamp01(local / 0.6);
        for (let i = 0; i < inner.length; i++) {
          const ph = TWO_PI * (local / period - i * phaseStep);
          const dy = Math.sin(ph) * amp * ramp;
          const rot = rotAmp ? Math.sin(ph + 0.7) * rotAmp * ramp : 0;
          inner[i].style.transform = rot ? `translateY(${dy.toFixed(2)}px) rotate(${rot.toFixed(2)}deg)` : `translateY(${dy.toFixed(2)}px)`;
        }
      }
    };
  }
  function compileFlicker(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = Math.max(0.2, fx.dur ?? 1.2);
    const idle = fx.idle ?? 0.08;
    const off = fx.off != null ? ctx.resolveT(fx.off, Infinity) : Infinity;
    const seed = fx.seed ?? 1;
    const n = seededSines(seed, 13);
    const nFast = seededSines(seed + 77, 31);
    return {
      apply(t, delta) {
        if (t < at) {
          delta.opacityMul = 0;
          return;
        }
        if (t >= off) {
          delta.opacityMul *= clamp01(1 - (t - off) / 0.12);
          return;
        }
        const local = t - at;
        if (local < dur) {
          const stability = local / dur;
          const spike = n(local) * 0.5 + nFast(local * 1.7) * 0.5;
          const gate = spike > 0.55 - stability * 0.9 ? 1 : 0.12 + stability * 0.3;
          delta.opacityMul *= gate;
        } else {
          delta.opacityMul *= 1 - Math.max(0, n(local * 0.6)) * idle;
        }
      }
    };
  }
  function compileScanReveal(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.9;
    const dir = fx.dir ?? "top";
    const color = fx.color ?? "var(--fx-accent)";
    const lineWidth = fx.lineWidth ?? 3;
    const glow = fx.glow !== false;
    const ease = easeOf(fx.ease ?? "inOutCubic");
    const doc = ctx.el.ownerDocument;
    const line = doc.createElement("div");
    line.className = "kp-scan-line";
    const vertical = dir === "top" || dir === "bottom";
    line.style.cssText = [
      "position:absolute",
      "pointer-events:none",
      "opacity:0",
      vertical ? `left:-6%;right:-6%;height:${lineWidth}px` : `top:-6%;bottom:-6%;width:${lineWidth}px`,
      `background:${color}`,
      glow ? `box-shadow:0 0 18px ${color},0 0 46px ${color}` : ""
    ].filter(Boolean).join(";");
    ctx.el.appendChild(line);
    return {
      apply(t, delta) {
        const p = ease(clamp01((t - at) / Math.max(1e-6, dur)));
        const pct = p * 100;
        switch (dir) {
          case "top":
            delta.clipPath = `inset(0 0 ${(100 - pct).toFixed(2)}% 0)`;
            break;
          case "bottom":
            delta.clipPath = `inset(${(100 - pct).toFixed(2)}% 0 0 0)`;
            break;
          case "left":
            delta.clipPath = `inset(0 ${(100 - pct).toFixed(2)}% 0 0)`;
            break;
          case "right":
            delta.clipPath = `inset(0 0 0 ${(100 - pct).toFixed(2)}%)`;
            break;
        }
        const active = p > 1e-3 && p < 0.999;
        line.style.opacity = active ? "1" : "0";
        if (active) {
          if (vertical) line.style.top = `${pct.toFixed(2)}%`;
          else line.style.left = `${pct.toFixed(2)}%`;
        }
      }
    };
  }
  function compileLiquidBlob(fx, ctx) {
    const period = Math.max(2, fx.period ?? 8);
    const amount = clamp01(fx.amount ?? 0.35);
    const seed = fx.seed ?? 1;
    const fns = [];
    for (let i = 0; i < 8; i++) fns.push(seededSines(seed + i * 37, 1 / period));
    const el = ctx.el;
    return {
      apply(t) {
        const r = (i) => (50 + fns[i](t) * 25 * amount * 2).toFixed(1);
        el.style.borderRadius = `${r(0)}% ${r(1)}% ${r(2)}% ${r(3)}% / ${r(4)}% ${r(5)}% ${r(6)}% ${r(7)}%`;
      }
    };
  }
  function compileOrbit(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const period = Math.max(0.5, fx.period ?? 6);
    const rx = fx.rx ?? 120;
    const ry = fx.ry ?? rx * 0.6;
    const phase0 = (fx.phase ?? 0) * Math.PI * 2;
    const sign = fx.dir === "ccw" ? -1 : 1;
    const depth = Boolean(fx.depth);
    const TWO_PI = Math.PI * 2;
    return {
      apply(t, delta) {
        const ph = phase0 + sign * TWO_PI * ((t - at) / period);
        delta.dx += Math.cos(ph) * rx;
        delta.dy += Math.sin(ph) * ry;
        if (depth) {
          const near = (Math.sin(ph) + 1) / 2;
          delta.dscale *= 0.75 + near * 0.5;
          delta.opacityMul *= 0.55 + near * 0.45;
        }
      }
    };
  }
  function compileSliceIn(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const dur = fx.dur ?? 0.7;
    const count = Math.max(2, Math.min(8, fx.slices ?? 4));
    const offset = fx.offset ?? 90;
    const horizontal = (fx.dir ?? "h") === "h";
    const ease = easeOf(fx.ease ?? "outExpo");
    const seed = fx.seed ?? 1;
    const rand = ((s) => {
      let a = Math.floor(s * 2654435761) >>> 0;
      return () => {
        a = a * 1664525 + 1013904223 >>> 0;
        return a / 4294967296;
      };
    })(seed);
    const parent = ctx.el;
    const doc = parent.ownerDocument;
    const holder = doc.createElement("div");
    holder.style.cssText = "position:absolute;inset:0;pointer-events:none";
    const slices = [];
    const src = parent.cloneNode(true);
    src.style.position = "absolute";
    src.style.inset = "0";
    for (let i = 0; i < count; i++) {
      const s = src.cloneNode(true);
      const a = (i / count * 100).toFixed(2);
      const b = (100 - (i + 1) / count * 100).toFixed(2);
      s.style.clipPath = horizontal ? `inset(${a}% 0 ${b}% 0)` : `inset(0 ${b}% 0 ${a}%)`;
      s.setAttribute("aria-hidden", "true");
      holder.appendChild(s);
      slices.push({ el: s, dir: rand() > 0.5 ? 1 : -1, mag: 0.6 + rand() * 0.8 });
    }
    const originals = [];
    for (const child of Array.from(parent.children)) {
      if (child === holder) continue;
      const el = child;
      originals.push({ el, vis: el.style.visibility });
      el.style.visibility = "hidden";
    }
    parent.appendChild(holder);
    return {
      apply(t) {
        const p = ease(clamp01((t - at) / Math.max(1e-6, dur)));
        const inv = 1 - p;
        const done = p >= 0.999;
        for (const o of originals) o.el.style.visibility = done ? o.vis || "" : "hidden";
        holder.style.visibility = done ? "hidden" : "visible";
        if (done) return;
        for (const s of slices) {
          const d = s.dir * s.mag * offset * inv;
          s.el.style.transform = horizontal ? `translateX(${d.toFixed(2)}px)` : `translateY(${d.toFixed(2)}px)`;
          s.el.style.opacity = String(clamp01(p * 2));
        }
      }
    };
  }
  function compileBreathe(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const period = Math.max(1, fx.period ?? 3.6);
    const amount = fx.amount ?? 0.02;
    const glowColor = fx.glowColor;
    const glowRadius = fx.glowRadius ?? 26;
    const el = ctx.el;
    const TWO_PI = Math.PI * 2;
    return {
      apply(t, delta) {
        const local = t - at;
        if (local < 0) return;
        const ramp = clamp01(local / 1.2);
        const s = Math.sin(TWO_PI * local / period);
        delta.dscale *= 1 + s * amount * ramp;
        if (glowColor) {
          const r = (glowRadius * (0.55 + (s + 1) / 2 * 0.45) * ramp).toFixed(1);
          el.style.filter = `drop-shadow(0 0 ${r}px ${glowColor})`;
        }
      }
    };
  }
  function compileJitter(fx, ctx) {
    const at = ctx.resolveT(fx.at, 0);
    const until = fx.until != null ? ctx.resolveT(fx.until, Infinity) : Infinity;
    const amp = fx.amp ?? 2.5;
    const freq = Math.max(1, fx.freq ?? 9);
    const rotAmp = fx.rotAmp ?? 0.8;
    const seed = fx.seed ?? 1;
    const nx = seededSines(seed, freq * 0.9);
    const ny = seededSines(seed + 53, freq * 1.1);
    const nr = seededSines(seed + 107, freq * 0.7);
    return {
      apply(t, delta) {
        if (t < at || t > until) return;
        const q = Math.floor((t - at) * freq) / freq;
        delta.dx += nx(q) * amp;
        delta.dy += ny(q) * amp;
        delta.drot += nr(q) * rotAmp;
      }
    };
  }
  function compileEffects(effects, ctx) {
    const perFrame = [];
    const ghosts = [];
    for (const fx of effects ?? []) {
      switch (fx.type) {
        case "kineticText":
          perFrame.push(compileKineticText(fx, ctx));
          break;
        case "maskReveal":
          perFrame.push(compileMaskReveal(fx, ctx));
          break;
        case "shake":
          perFrame.push(compileShake(fx, ctx));
          break;
        case "lineDraw":
          perFrame.push(compileLineDraw(fx, ctx));
          break;
        case "numberRoll":
          perFrame.push(compileNumberRoll(fx, ctx));
          break;
        case "trail":
          ghosts.push(...compileTrail(fx, ctx).ghosts);
          break;
        case "magnify":
          perFrame.push(compileMagnify(fx, ctx));
          break;
        case "typewriter":
          perFrame.push(compileTypewriter(fx, ctx));
          break;
        case "glitch":
          perFrame.push(compileGlitch(fx, ctx));
          break;
        case "shine":
          perFrame.push(compileShine(fx, ctx));
          break;
        case "gradientShift":
          perFrame.push(compileGradientShift(fx, ctx));
          break;
        case "pathMove":
          perFrame.push(compilePathMove(fx, ctx));
          break;
        case "waveText":
          perFrame.push(compileWaveText(fx, ctx));
          break;
        case "flicker":
          perFrame.push(compileFlicker(fx, ctx));
          break;
        case "scanReveal":
          perFrame.push(compileScanReveal(fx, ctx));
          break;
        case "liquidBlob":
          perFrame.push(compileLiquidBlob(fx, ctx));
          break;
        case "orbit":
          perFrame.push(compileOrbit(fx, ctx));
          break;
        case "sliceIn":
          perFrame.push(compileSliceIn(fx, ctx));
          break;
        case "breathe":
          perFrame.push(compileBreathe(fx, ctx));
          break;
        case "jitter":
          perFrame.push(compileJitter(fx, ctx));
          break;
      }
    }
    return { perFrame, ghosts };
  }

  // src/lib/motion/runtime/hydrate.ts
  var STAGE_W = 1920;
  var STAGE_H = 1080;
  function applyTransform(el, v, delta, camX, camY, parallax) {
    const px = (parallax - 1) * camX;
    const py = (parallax - 1) * camY;
    const x = v.x + delta.dx + px;
    const y = v.y + delta.dy + py;
    const rot = v.rotate + delta.drot;
    const scale = v.scale * delta.dscale;
    el.style.transform = `translate(${x.toFixed(2)}px, ${y.toFixed(2)}px) rotate(${rot.toFixed(3)}deg) scale(${(scale * v.scaleX).toFixed(4)}, ${(scale * v.scaleY).toFixed(4)})`;
    el.style.opacity = String(clamp01(v.opacity * delta.opacityMul));
    el.style.clipPath = delta.clipPath ?? "";
    el.style.filter = v.blur > 0.01 ? `blur(${v.blur.toFixed(2)}px)` : "";
  }
  function compileLayer(spec, layer, el) {
    const resolveT = (ref, fb) => resolveTimeRef(ref, spec.beats, fb);
    const tracks = (layer.tracks ?? []).map((tr) => compileTrack(tr, resolveT));
    const effects = compileEffects(layer.effects, { el, resolveT, stageW: STAGE_W, stageH: STAGE_H });
    return {
      el,
      inSec: resolveT(layer.in, 0),
      outSec: resolveT(layer.out, spec.duration),
      parallax: layer.parallax ?? 1,
      tracks,
      effects,
      ghosts: effects.ghosts,
      delta: { dx: 0, dy: 0, drot: 0, dscale: 1, opacityMul: 1, clipPath: null },
      values: { ...TRACK_DEFAULTS }
    };
  }
  function hydrateScene(host) {
    if (host.__kpSceneInstance) {
      return host.__kpSceneInstance;
    }
    const specEl = host.matches("script[data-kp-scene-spec]") ? host : host.querySelector("script[data-kp-scene-spec]");
    if (!specEl?.textContent) return null;
    let spec;
    try {
      spec = JSON.parse(specEl.textContent);
    } catch {
      return null;
    }
    const sceneRoot = host.matches(".kp-scene") ? host : host.querySelector(".kp-scene");
    if (!sceneRoot) return null;
    const resolveT = (ref, fb) => resolveTimeRef(ref, spec.beats, fb);
    const layers = [];
    const bindLayers = (defs, prefix) => {
      for (const def of defs) {
        const id = prefix ? `${prefix}/${def.id}` : def.id;
        const el = sceneRoot.querySelector(`[data-kp-layer-id="${cssEscape(id)}"]`);
        if (el) layers.push(compileLayer(spec, def, el));
        if (def.kind === "group" && def.children) bindLayers(def.children, id);
      }
    };
    bindLayers(spec.layers, "");
    const camEl = sceneRoot.querySelector(".kp-cam");
    const camTracks = (spec.camera?.tracks ?? []).map((tr) => compileTrack(tr, resolveT));
    const flashes = [];
    const flashEl = sceneRoot.querySelector(".kp-flash");
    if (flashEl) {
      for (const f of spec.flashes ?? []) {
        flashes.push({
          at: resolveT(f.at, 0),
          dur: f.dur ?? 0.3,
          peak: f.peak ?? 0.75,
          el: flashEl
        });
        if (f.color) flashEl.style.background = f.color;
      }
    }
    const flashEase = easeOf("outQuad");
    const camValues = { ...TRACK_DEFAULTS };
    const instance = {
      root: sceneRoot,
      duration: spec.duration,
      renderFrame(t) {
        let camX = 0;
        let camY = 0;
        if (camEl) {
          const cv = evalTracks(camTracks, t);
          Object.assign(camValues, cv);
          camX = cv.x;
          camY = cv.y;
          camEl.style.transform = `translate(${cv.x.toFixed(2)}px, ${cv.y.toFixed(2)}px) rotate(${cv.rotate.toFixed(3)}deg) scale(${cv.scale.toFixed(4)})`;
        }
        for (const layer of layers) {
          const visible = t >= layer.inSec && t < layer.outSec;
          layer.el.style.visibility = visible ? "visible" : "hidden";
          if (!visible) {
            for (const g of layer.ghosts) g.el.style.visibility = "hidden";
            continue;
          }
          const v = evalTracks(layer.tracks, t);
          Object.assign(layer.values, v);
          resetDelta(layer.delta);
          for (const fx of layer.effects.perFrame) fx.apply(t, layer.delta);
          applyTransform(layer.el, layer.values, layer.delta, camX, camY, layer.parallax);
          for (const g of layer.ghosts) {
            const gt = Math.max(layer.inSec, t - g.lag);
            const gv = evalTracks(layer.tracks, gt);
            g.el.style.visibility = "visible";
            g.el.style.transform = `translate(${gv.x.toFixed(2)}px, ${gv.y.toFixed(2)}px) rotate(${gv.rotate.toFixed(3)}deg) scale(${(gv.scale * gv.scaleX).toFixed(4)}, ${(gv.scale * gv.scaleY).toFixed(4)})`;
            g.el.style.opacity = String(clamp01(gv.opacity * g.fade));
          }
        }
        if (flashEl) {
          let peak = 0;
          for (const f of flashes) {
            const local = t - f.at;
            if (local < 0 || local > f.dur) continue;
            const p = local / f.dur;
            const env = p < 0.25 ? p / 0.25 : 1 - flashEase((p - 0.25) / 0.75);
            peak = Math.max(peak, f.peak * env);
          }
          flashEl.style.opacity = String(peak);
        }
      },
      dispose() {
        for (const layer of layers) {
          for (const g of layer.ghosts) g.el.remove();
        }
        delete host.__kpSceneInstance;
      }
    };
    host.__kpSceneInstance = instance;
    instance.renderFrame(0);
    return instance;
  }
  function cssEscape(s) {
    return s.replace(/["\\\]]/g, "\\$&");
  }

  // src/lib/motion/runtime/index.ts
  var VERSION = true ? "a274e2e924" : "dev";
  function findHosts(root) {
    const hosts = [];
    root.querySelectorAll("script[data-kp-scene-spec]").forEach((specEl) => {
      const host = specEl.closest("[data-kp-layer]") ?? specEl.parentElement;
      if (host) hosts.push(host);
    });
    return hosts;
  }
  var KPMotion = {
    version: VERSION,
    hydrate(host) {
      return hydrateScene(host);
    },
    hydrateAll(root) {
      const out = [];
      for (const host of findHosts(root)) {
        const inst = hydrateScene(host);
        if (inst) out.push(inst);
      }
      return out;
    },
    renderFrame(host, t) {
      const cached = host.__kpSceneInstance;
      const inst = cached ?? hydrateScene(host);
      inst?.renderFrame(t);
    },
    dispose(host) {
      host.__kpSceneInstance?.dispose();
    }
  };
  (function bootstrap() {
    if (typeof window === "undefined") return;
    window.KPMotion = KPMotion;
    if (typeof window.__kunpengRenderLayerFrame !== "function") {
      window.__kunpengRenderLayerFrame = (layer, localSec) => {
        if (layer.querySelector("script[data-kp-scene-spec]")) {
          KPMotion.renderFrame(layer, localSec);
        }
      };
    }
    if (typeof document !== "undefined" && typeof window.__kunpengRenderFrame !== "function") {
      const bindGlobal = () => {
        const stage = document.getElementById("stage") ?? document.body;
        if (!stage || !stage.querySelector("script[data-kp-scene-spec]")) return;
        if (stage.querySelector("[data-kp-layer]")) return;
        window.__kunpengRenderFrame = (t) => {
          for (const inst of KPMotion.hydrateAll(stage)) inst.renderFrame(t);
        };
      };
      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", bindGlobal, { once: true });
      } else {
        bindGlobal();
      }
    }
  })();
})();
